---
- name: Ensure OpenSSH, OpenSSL, and Docker are installed with the latest versions
  hosts: all
  gather_facts: false
  become: true

  tasks:
    # Checking if OpenSSH is installed
    - name: Checking if OpenSSH is installed
      shell: ssh -V
      register: openssh_installed
      ignore_errors: yes

    - name: Display OpenSSH version if installed
      ansible.builtin.debug:
        msg: "OpenSSH version: {{ openssh_installed.stdout | default(openssh_installed.stderr) | default('not installed') }}"
      when: openssh_installed.rc == 0

    # Checking if OpenSSL is installed
    - name: Checking if OpenSSL is installed
      shell: openssl version
      register: openssl_installed
      ignore_errors: yes

    - name: Display OpenSSL version if installed
      ansible.builtin.debug:
        msg: "OpenSSL version: {{ openssl_installed.stdout | default(openssl_installed.stderr) | default('not installed') }}"
      when: openssl_installed.rc == 0

    # Checking if Docker is installed
    - name: Checking Docker version
      shell: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Display Docker version if installed
      ansible.builtin.debug:
        msg: "Docker version is {{ docker_version.stdout | default('not installed') }}"
      when: docker_version.rc == 0

    # Installing Docker on Ubuntu
    - name: Install Docker on Ubuntu
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: docker_version.rc != 0 and ansible_facts['os_family'] == 'Debian'

    # Installing Docker on Amazon Linux 
    - name: Install Docker on Amazon Linux
      ansible.builtin.yum:
        name: docker
        state: present
      become: true
      when: docker_version.rc != 0 and ansible_facts['os_family'] == 'RedHat'

    # Start and enable Docker service
    # - name: Ensure Docker service is running
    #   ansible.builtin.service:
    #     name: docker
    #     state: stopped
    #     enabled: false

    # Recheck Docker version after installation
    - name: Rechecking Docker version after installation
      shell: docker --version
      register: docker_version_after_install
      when: docker_version.rc != 0
      ignore_errors: yes

    - name: Display Docker version after installation
      ansible.builtin.debug:
        msg: "Docker version is {{ docker_version_after_install.stdout | default('not installed') }}"
      when: docker_version_after_install.rc == 0
